ACROSS_DATASET_CLASSES = {
    # "tuberlin": [
    #     "wrist-watch",
    #     "mermaid",
    #     "mosquito",
    #     "purse",
    #     "house",
    #     "baseball bat",
    #     "toilet",
    #     "panda",
    #     "butterfly",
    #     "mug",
    #     "wineglass",
    #     "screwdriver",
    #     "skull",
    #     "truck",
    #     "palm tree",
    #     "cell phone",
    #     "horse",
    #     "suv",
    #     "floor lamp",
    #     "pipe (for smoking)",
    #     "tv",
    # ],
    "tuberlin": [
        "bus",
        "tractor",
        "suitcase",
        "streetlight",
        "telephone",
        "bottle opener",
        "canoe",
        "teacup",
        "laptop",
        "lighter",
        "brain",
        "t-shirt",
        "trombone",
        "windmill",
        "snowboard",
        "rollerblades",
        "parachute",
        "space shuttle",
        "bridge",
        "frying-pan",
        "horse"
    ],
    "quickdraw": [
        "scissors",
        "tree",
        "windmill",
        "feather",
        "campfire",
        "palm tree",
        "fire_hydrant",
        "beach",
        "megaphone",
        "cactus",
        "cake"
    ],
    # "quickdraw": [
    #     "bandage",
    #     "beach",
    #     "bus",
    #     "cake",
    #     "campfire",
    #     "cruise ship",
    #     "eiffel tower",
    #     "fire_hydrant",
    #     "map",
    #     "megaphone",
    #     "moon",
    # ],
}

# Backward-compatible alias for any earlier local imports.
USEEN_CLASSES = ACROSS_DATASET_CLASSES
'''
"palm tree",
"parrot",
"windmill"
'''