ACROSS_DATASET_CLASSES = {
    "tuberlin": [
        "wrist-watch",
        "mermaid",
        "mosquito",
        "cup",
        "house",
        "baseball bat",
        "toilet",
        "panda",
        "butterfly",
        "mug",
        "wineglass",
        "bus",
        "skull",
        "truck",
        "palm tree",
        "cell phone",
        "horse",
        "suv",
        "floor lamp",
        "airplane",
        "tv",
    ],
    "quickdraw": [
        "bandage",
        "beach",
        "bus",
        "cake",
        "campfire",
        "cruise ship",
        "eiffel tower",
        "fire_hydrant",
        "map",
        "megaphone",
        "moon",
        "palm tree",
        "parrot",
        "windmill"
    ],
}

