UNSEEN_CLASSES = {
    "sketchy_1": [
        "cup",
        "swan",
        "harp",
        "squirrel",
        "snail",
        "ray",
        "pineapple",
        "volcano",
        "rifle",
        "scissors",
        "parrot",
        "windmill",
        "teddy_bear",
        "tree",
        "wine_bottle",
        "deer",
        "chicken",
        "hotdog",
        "wheelchair",
        "tank",
        "umbrella",
        "butterfly",
        "camel",
        "horse",
        "bell"
    ],

    "sketchy_2": [
        "bat",
        "cabin",
        "cow",
        "dolphin",
        "door",
        "giraffe",
        "helicopter",
        "mouse",
        "pear",
        "raccoon",
        "rhinoceros",
        "saw",
        "scissors",
        "seagull",
        "skyscraper",
        "songbird",
        "sword",
        "tree",
        "wheelchair",
        "windmill",
        "window",
    ],

    "quickdraw": [
        "alarm_clock",
        "axe",
        "bandage",
        "bat",
        "beach",
        "bread",
        "bus",
        "cake",
        "campfire",
        "cruise ship",
        "dolphin",
        "eiffel tower",
        "eyeglasses",
        "fire_hydrant",
        "flower",
        "giraffe",
        "hamburger",
        "helicopter",
        "hot-air_balloon",
        "kangaroo",
        "map",
        "megaphone",
        "moon",
        "motorcycle",
        "palm tree",
        "parrot",
        "raccoon",
        "sailboat",
        "skyscraper",
        "windmill",
    ],

    # "quickdraw": [
    #     "helicopter",
    #     "moon",
    #     "spider",
    #     "pineapple",
    #     "hammer",
    #     "banana",
    #     "owl",
    #     "teddy_bear",
    #     "scorpion",
    #     "chair",
    #     "motorcycle",
    #     "bread",
    #     "train",
    #     "butterfly",
    #     "palm tree",
    #     "cake",
    #     "zebra",
    #     "lighthouse",
    #     "pickup_truck",
    #     "church",
    #     "dog",
    #     "couch",
    #     "skyscraper",
    #     "sheep",
    #     "fan"
    #     "bee",
    #     "snake",
    #     "shark",
    #     "eyeglasses",
    #     "violin",
    # ],

    # "tuberlin": [
    #     "airplane",
    #     "alarm clock",
    #     "angel",
    #     "ant",
    #     "apple",
    #     "armchair",
    #     "axe",
    #     "backpack",
    #     "barn",
    #     "tennis-racket",
    #     "bathtub",
    #     "bear (animal)",
    #     "bee",
    #     "beer-mug",
    #     "bell",
    #     "bicycle",
    #     "binoculars",
    #     "blimp",
    #     "bottle opener",
    #     "brain",
    #     "bus",
    #     "cactus",
    #     "calculator",
    #     "camel",
    #     "canoe",
    #     "car (sedan)",
    #     "castle",
    #     "chandelier",
    #     "cigarette",
    #     "computer monitor",
    # ],
    
    "tuberlin": [
        "helicopter",
        "wrist-watch",
        "mermaid",
        "mosquito",
        "pear",
        "couch",
        "hammer",
        "purse",
        "house",
        "baseball bat",
        "toilet",
        "panda",
        "butterfly",
        "mug",
        "wineglass",
        "motorbike",
        "eyeglasses",
        "hot air balloon",
        "screwdriver",
        "skull",
        "truck",
        "palm tree",
        "cell phone",
        "horse",
        "sailboat",
        "suv",
        "church",
        "floor lamp",
        "pipe (for smoking)",
        "tv",
    ],
}

GENERALIZED_CLASSES = {
    "sketchy_2": {
        "teapot",
        "harp",
        "piano",
        "trumpet",
        "saxophone",
        "hourglass",
        "mushroom",
        "pretzel",
        "bell"
    },
    
    "tuberlin": {
        "airplane",
        "blimp",
        "tablelamp",
        "telephone",
        "human-skeleton",
        "pickup truck"
    }
}